### PR TITLE
add flag to enable MulticastDNS

### PR DESCRIPTION
**Pull request by Finkregh**

### CODE REVIEW

**Comment by erikh** [comment]
LGTM

**Comment by erikh** [comment]
@laduke

**Comment by laduke** [comment]
Seems right. I feel like we had added this by default or something. Guess not. 

Let me try to run it on a computer.

**Comment by erikh** [comment]
let me know if you need help with the release process, send me an email privately if you do.

------- Original Message -------

**Comment by Finkregh** [comment]
Anything i can do here?

(sorry, fat-fingered the close/open 🙄 )

**Comment by Finkregh** [comment]
I

**Comment by laduke** [comment]
Sorry for the delay. Just haven't had bandwidth to look at it. 

One thing I'm thinking: eventually we'll have a flag for every option in `systemd.network`. 
I'm wondering if there's a way around that. 

What if the user could specify their own template, for example? 

Then people wouldn't have to come plead for new flags.

**Comment by laduke** [comment]
Seems to work. 

Resolvectl with and without -multicast-dns
```
         Protocols: -DefaultRoute +LLMNR +mDNS -DNSOverTLS DNSSEC=no/unsupported
```
```
         Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

**Pull request merged**
